# Form implementation generated from reading ui file 'D:\Code\testpy\ui_designer\forms\login_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from ui_designer.designer_styles import StyleApplicator

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(450, 350)
        LoginDialog.setModal(True)
        self.main_layout = QtWidgets.QVBoxLayout(LoginDialog)
        self.main_layout.setContentsMargins(30, 30, 30, 30)
        self.main_layout.setSpacing(20)
        self.main_layout.setObjectName("main_layout")
        self.title_label = QtWidgets.QLabel(parent=LoginDialog)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.main_layout.addWidget(self.title_label)
        self.subtitle_label = QtWidgets.QLabel(parent=LoginDialog)
        self.subtitle_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtitle_label.setObjectName("subtitle_label")
        self.main_layout.addWidget(self.subtitle_label)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.main_layout.addItem(spacerItem)
        self.form_frame = QtWidgets.QFrame(parent=LoginDialog)
        self.form_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.form_frame.setObjectName("form_frame")
        self.form_layout = QtWidgets.QFormLayout(self.form_frame)
        self.form_layout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.form_layout.setSpacing(16)
        self.form_layout.setObjectName("form_layout")
        self.username_label = QtWidgets.QLabel(parent=self.form_frame)
        self.username_label.setObjectName("username_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.username_label)
        self.username_edit = QtWidgets.QLineEdit(parent=self.form_frame)
        self.username_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.username_edit.setObjectName("username_edit")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.username_edit)
        self.password_label = QtWidgets.QLabel(parent=self.form_frame)
        self.password_label.setObjectName("password_label")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.password_label)
        self.password_edit = QtWidgets.QLineEdit(parent=self.form_frame)
        self.password_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_edit.setObjectName("password_edit")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.password_edit)
        self.main_layout.addWidget(self.form_frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.main_layout.addItem(spacerItem1)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setSpacing(12)
        self.button_layout.setObjectName("button_layout")
        self.setup_btn = QtWidgets.QPushButton(parent=LoginDialog)
        self.setup_btn.setMinimumSize(QtCore.QSize(100, 45))
        self.setup_btn.setObjectName("setup_btn")
        self.button_layout.addWidget(self.setup_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem2)
        self.login_btn = QtWidgets.QPushButton(parent=LoginDialog)
        self.login_btn.setMinimumSize(QtCore.QSize(120, 45))
        self.login_btn.setDefault(True)
        self.login_btn.setObjectName("login_btn")
        self.button_layout.addWidget(self.login_btn)
        self.main_layout.addLayout(self.button_layout)
        self.language_layout = QtWidgets.QHBoxLayout()
        self.language_layout.setObjectName("language_layout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.language_layout.addItem(spacerItem3)
        self.language_label = QtWidgets.QLabel(parent=LoginDialog)
        self.language_label.setObjectName("language_label")
        self.language_layout.addWidget(self.language_label)
        self.language_selector = QtWidgets.QComboBox(parent=LoginDialog)
        self.language_selector.setMinimumSize(QtCore.QSize(100, 30))
        self.language_selector.setObjectName("language_selector")
        self.language_selector.addItem("")
        self.language_selector.addItem("")
        self.language_layout.addWidget(self.language_selector)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.language_layout.addItem(spacerItem4)
        self.main_layout.addLayout(self.language_layout)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)


    def apply_styles(self):
        """Apply designer-friendly styles to widgets"""
        # Apply styles using StyleApplicator
        # Example usage:
        # StyleApplicator.apply_primary_button(self.save_btn)
        # StyleApplicator.apply_input_field(self.name_edit)
        # StyleApplicator.apply_table(self.table_widget)
        pass

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Login - Psychological Records"))
        self.title_label.setText(_translate("LoginDialog", "🧠 Psychological Records"))
        self.subtitle_label.setText(_translate("LoginDialog", "Secure Login Required"))
        self.username_label.setText(_translate("LoginDialog", "Username:"))
        self.username_edit.setPlaceholderText(_translate("LoginDialog", "Enter username"))
        self.password_label.setText(_translate("LoginDialog", "Password:"))
        self.password_edit.setPlaceholderText(_translate("LoginDialog", "Enter password"))
        self.setup_btn.setText(_translate("LoginDialog", "⚙️ Setup"))
        self.login_btn.setText(_translate("LoginDialog", "🔐 Login"))
        self.language_label.setText(_translate("LoginDialog", "Language:"))
        self.language_selector.setItemText(0, _translate("LoginDialog", "🇺🇸 EN"))
        self.language_selector.setItemText(1, _translate("LoginDialog", "🇷🇴 RO"))
