# Form implementation generated from reading ui file 'D:\Code\testpy\ui_designer\forms\person_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from ui_designer.designer_styles import StyleApplicator

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PersonDialog(object):
    def setupUi(self, PersonDialog):
        PersonDialog.setObjectName("PersonDialog")
        PersonDialog.resize(500, 400)
        PersonDialog.setModal(True)
        self.main_layout = QtWidgets.QVBoxLayout(PersonDialog)
        self.main_layout.setContentsMargins(20, 20, 20, 20)
        self.main_layout.setSpacing(16)
        self.main_layout.setObjectName("main_layout")
        self.title_label = QtWidgets.QLabel(parent=PersonDialog)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.main_layout.addWidget(self.title_label)
        self.form_frame = QtWidgets.QFrame(parent=PersonDialog)
        self.form_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.form_frame.setObjectName("form_frame")
        self.form_layout = QtWidgets.QFormLayout(self.form_frame)
        self.form_layout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.form_layout.setHorizontalSpacing(16)
        self.form_layout.setVerticalSpacing(12)
        self.form_layout.setObjectName("form_layout")
        self.name_label = QtWidgets.QLabel(parent=self.form_frame)
        self.name_label.setObjectName("name_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.name_label)
        self.name_edit = QtWidgets.QLineEdit(parent=self.form_frame)
        self.name_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.name_edit.setObjectName("name_edit")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name_edit)
        self.cnp_label = QtWidgets.QLabel(parent=self.form_frame)
        self.cnp_label.setObjectName("cnp_label")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.cnp_label)
        self.cnp_edit = QtWidgets.QLineEdit(parent=self.form_frame)
        self.cnp_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.cnp_edit.setMaxLength(13)
        self.cnp_edit.setObjectName("cnp_edit")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cnp_edit)
        self.phone_label = QtWidgets.QLabel(parent=self.form_frame)
        self.phone_label.setObjectName("phone_label")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.phone_label)
        self.phone_edit = QtWidgets.QLineEdit(parent=self.form_frame)
        self.phone_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.phone_edit.setObjectName("phone_edit")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phone_edit)
        self.email_label = QtWidgets.QLabel(parent=self.form_frame)
        self.email_label.setObjectName("email_label")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.email_label)
        self.email_edit = QtWidgets.QLineEdit(parent=self.form_frame)
        self.email_edit.setMinimumSize(QtCore.QSize(0, 40))
        self.email_edit.setObjectName("email_edit")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.email_edit)
        self.notes_label = QtWidgets.QLabel(parent=self.form_frame)
        self.notes_label.setObjectName("notes_label")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.notes_label)
        self.notes_edit = QtWidgets.QTextEdit(parent=self.form_frame)
        self.notes_edit.setMinimumSize(QtCore.QSize(0, 80))
        self.notes_edit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.notes_edit.setObjectName("notes_edit")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.notes_edit)
        self.main_layout.addWidget(self.form_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.main_layout.addItem(spacerItem)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setSpacing(12)
        self.button_layout.setObjectName("button_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem1)
        self.cancel_btn = QtWidgets.QPushButton(parent=PersonDialog)
        self.cancel_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.cancel_btn.setObjectName("cancel_btn")
        self.button_layout.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(parent=PersonDialog)
        self.save_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.save_btn.setDefault(True)
        self.save_btn.setObjectName("save_btn")
        self.button_layout.addWidget(self.save_btn)
        self.main_layout.addLayout(self.button_layout)

        self.retranslateUi(PersonDialog)
        self.cancel_btn.clicked.connect(PersonDialog.reject) # type: ignore
        self.save_btn.clicked.connect(PersonDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PersonDialog)


    def apply_styles(self):
        """Apply designer-friendly styles to widgets"""
        # Apply styles using StyleApplicator
        # Example usage:
        # StyleApplicator.apply_primary_button(self.save_btn)
        # StyleApplicator.apply_input_field(self.name_edit)
        # StyleApplicator.apply_table(self.table_widget)
        pass

    def retranslateUi(self, PersonDialog):
        _translate = QtCore.QCoreApplication.translate
        PersonDialog.setWindowTitle(_translate("PersonDialog", "Add/Edit Person"))
        self.title_label.setText(_translate("PersonDialog", "Person Information"))
        self.name_label.setText(_translate("PersonDialog", "Full Name:"))
        self.name_edit.setPlaceholderText(_translate("PersonDialog", "Enter full name"))
        self.cnp_label.setText(_translate("PersonDialog", "CNP:"))
        self.cnp_edit.setPlaceholderText(_translate("PersonDialog", "Enter CNP (13 digits)"))
        self.phone_label.setText(_translate("PersonDialog", "Phone:"))
        self.phone_edit.setPlaceholderText(_translate("PersonDialog", "Enter phone number (optional)"))
        self.email_label.setText(_translate("PersonDialog", "Email:"))
        self.email_edit.setPlaceholderText(_translate("PersonDialog", "Enter email address (optional)"))
        self.notes_label.setText(_translate("PersonDialog", "Notes:"))
        self.notes_edit.setPlaceholderText(_translate("PersonDialog", "Additional notes (optional)"))
        self.cancel_btn.setText(_translate("PersonDialog", "Cancel"))
        self.save_btn.setText(_translate("PersonDialog", "Save"))
