# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run_unified.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('locales/', 'locales/'),
        ('src/', 'src/'),
        ('assets/app_icon.ico', '.'),
        ('assets/app_icon.png', '.'),
        ('settings.json', '.'),
    ],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui', 
        'PyQt6.QtWidgets',
        'PyQt6.QtPrintSupport',
        'cryptography',
        'cryptography.fernet',
        'bcrypt',
        'sqlite3',
        'json',
        'os',
        'sys',
        'hashlib',
        'src.utils.language_manager',
        'src.utils.app_translator',
        'src.utils.language_aware_mixin',
        'src.utils.material_theme',
        'src.utils.material_elevation',
        'src.utils.theme_manager',
        'src.utils.pdf_generator',
        'src.utils.system_theme_detector',
        'src.core.database',
        'src.ui.unified_main_window',
        'src.ui.add_patient_dialog',
        'src.ui.add_session_dialog',
        'src.ui.add_checkup_dialog',
        'src.ui.edit_session_dialog',
        'src.ui.edit_checkup_dialog',
        'src.ui.password_dialog',
        'src.ui.language_selector_dialog',
        'src.ui.select_record_dialog',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'email',
        'http',
        'urllib',
        'xml',
        'test',
        'tests',
        'pytest',
        'unittest'
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='PsychologicalRecords',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/app_icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='PsychologicalRecords',
)

